### ISSUE TITLE
Must enter "feed" manually tag in settings 

### ISSUE THREAD

**Issue by bfcs** [aoout/obsidian-rss-copyist#5]
by default, feed note tag is "feed", but when the settings is empty, the command"Rss Copyist: Get the newest articles from the feed" is not shown.
<img width="685" alt="image" src="https://github.com/aoout/obsidian-rss-copyist/assets/52602045/95d5cbfb-1796-4c28-aa74-683cbb030305">

by the way, newlest should be newest?

**Comment by aoout** [comment]
Sorry for my bad English.

**Comment by aoout** [comment]
> but when the settings is empty, the command"Rss Copyist: Get the newest articles from the feed" is not shown.

Why setttings is empty? The tag is needed to identify whether it is a feed.

**Comment by bfcs** [comment]
Hi, @aoout 
<img width="817" alt="image" src="https://github.com/aoout/obsidian-rss-copyist/assets/52602045/2e14fe62-4c32-48bd-82cd-d36b950cecd7">

**Comment by aoout** [comment]
I just don't understand your meaning.
